Usage: celery [OPTIONS] COMMAND [ARGS]...
Try 'celery --help' for help.

Error: Invalid value for '-A' / '--app': 
Unable to load celery application.
While trying to load the module truth_will_set_you_free the following error occurred:
Traceback (most recent call last):
  File "/home/jan/PycharmProjects/truth_will_set_you_free/venv/lib/python3.12/site-packages/celery/bin/celery.py", line 58, in convert
    return find_app(value)
           ^^^^^^^^^^^^^^^
  File "/home/jan/PycharmProjects/truth_will_set_you_free/venv/lib/python3.12/site-packages/celery/app/utils.py", line 383, in find_app
    sym = symbol_by_name(app, imp=imp)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jan/PycharmProjects/truth_will_set_you_free/venv/lib/python3.12/site-packages/kombu/utils/imports.py", line 59, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jan/PycharmProjects/truth_will_set_you_free/venv/lib/python3.12/site-packages/celery/utils/imports.py", line 109, in import_from_cwd
    return imp(module, package=package)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1325, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 929, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/jan/PycharmProjects/truth_will_set_you_free/truth_will_set_you_free/__init__.py", line 5, in <module>
    from .celery import app as celery_app
  File "/home/jan/PycharmProjects/truth_will_set_you_free/truth_will_set_you_free/celery.py", line 16, in <module>
    from apps.analyses.tasks import perform_analysis
  File "/home/jan/PycharmProjects/truth_will_set_you_free/apps/analyses/tasks.py", line 4, in <module>
    from .views import sentiment_analysis  # This imports your analysis function
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jan/PycharmProjects/truth_will_set_you_free/apps/analyses/views.py", line 6, in <module>
    from .modules.nlp_analysis import analyze_text as nlp_analyze_text
  File "/home/jan/PycharmProjects/truth_will_set_you_free/apps/analyses/modules/nlp_analysis.py", line 4, in <module>
    from apps.analyses.models import TextAnalysis
  File "/home/jan/PycharmProjects/truth_will_set_you_free/apps/analyses/models.py", line 3, in <module>
    class TextAnalysis(models.Model):
  File "/home/jan/PycharmProjects/truth_will_set_you_free/venv/lib/python3.12/site-packages/django/db/models/base.py", line 129, in __new__
    app_config = apps.get_containing_app_config(module)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jan/PycharmProjects/truth_will_set_you_free/venv/lib/python3.12/site-packages/django/apps/registry.py", line 260, in get_containing_app_config
    self.check_apps_ready()
  File "/home/jan/PycharmProjects/truth_will_set_you_free/venv/lib/python3.12/site-packages/django/apps/registry.py", line 138, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

